version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./image/Dockerfile.backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../image/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
