export const Organizer = [
    "AAGO",
    "ABC Central FL",
    "ABC SWFL",
    "ABC TB",
    // "AMFP TB",
    // "AMFP CF",
    // "BAAA",
    "BAMA",
    "BOMA ORL",
    "BOMA TB",
    "CAI CF",
    "CAI Suncoast",
    "CAI SWFL",
    // "CAI West FL",
    "CCC Orlando",
    "CCIM ORL",
    "CCIM SWFL",
    "CCIM WEST COAST",
    "CFCAR",
    "CFHLA",
    "CLAB",
    "COAA",
    "COMA",
    "CREW ORL",
    "CREW SRQ",
    "CREW SWFL",
    "CREW TB",
    "CoreNet",
    "FGCAR",
    "GCBX",
    // "ICSC",
    "IFMA ORL",
    "IFMA TB",
    "IREM ORL",
    "IREM TB",
    "MACF",
    // "MSCA",
    "NAIOP ORL",
    "NAIOP TB",
    "REIC",
    "REIS",
    "SAMA",
    "SMPS CF",
    "SMPS TB",
    "SOREP",
    "SRMA",
    "SWFAA",
    "TBRA",
    "ULI CF",
    "ULI SWFL",
    "ULI TB"
]
